import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import TopNav from "../../components/TopNav";
import Footer from "../../components/Footer";
const BENEFITS = [
    { icon: "🌍", title: "Pan-African reach", desc: "Get discovered by qualified students from all 54 African countries — not just your home market." },
    { icon: "✓", title: "Pre-verified applicants", desc: "Every student's documents are pre-checked before applications reach you." },
    { icon: "⚡", title: "Faster processing", desc: "Standardised applications and centralised communication cut admissions processing time significantly." },
    { icon: "📊", title: "Real-time analytics", desc: "Track applications, conversion rates, and enrolment trends by country, programme, and cohort." },
    { icon: "🎯", title: "Higher quality applications", desc: "Profile matching means students apply to programmes that fit — improving yield." },
    { icon: "🤝", title: "Direct student engagement", desc: "Message students, invite them to interviews, and send offers directly through the platform." },
];
const STEPS = [
    { n: "1", title: "Sign the partnership", desc: "Complete a short institutional agreement outlining programmes, tuition, and admissions criteria." },
    { n: "2", title: "Upload your programmes", desc: "We help you upload your programme catalogue, admission requirements, and intake schedules." },
    { n: "3", title: "Receive applications", desc: "Get verified applications, complete with documents and quality checks pre-applied." },
    { n: "4", title: "Send offers, enrol students", desc: "Review, interview, and send offers directly through R-Pro Apply. Track every step." },
];
export default function InstitutionsPage() {
    return (_jsxs("div", { className: "font-sans bg-white text-ink", children: [_jsx(TopNav, {}), _jsx("div", { className: "bg-ink text-white px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-5xl mx-auto grid md:grid-cols-[1.2fr_1fr] gap-12 items-center", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-widest text-brand font-bold mb-3", children: "Partner Institutions" }), _jsxs("h1", { className: "font-display font-black text-5xl tracking-tight leading-tight mb-5", children: ["Grow your enrolment.", _jsx("br", {}), _jsx("span", { className: "text-brand", children: "Diversify your campus." })] }), _jsx("p", { className: "text-white/70 leading-relaxed mb-7", children: "Join thousands of African universities, polytechnics, colleges, and apprenticeships on R-Pro Apply. Receive quality applications from verified students across all 54 African countries." }), _jsx(Link, { to: "/register", className: "btn-primary inline-block", children: "Become a Partner Institution \u2192" })] }), _jsxs("div", { className: "bg-white/5 border border-white/10 rounded-2xl p-7", children: [_jsx("p", { className: "text-xs uppercase tracking-widest text-white/50 font-bold mb-4", children: "Dashboard Preview" }), [
                                    { l: "Applications This Month", v: "342" },
                                    { l: "Verified Documents", v: "1,246" },
                                    { l: "Cross-Border Enrolments", v: "87" },
                                ].map((s) => (_jsxs("div", { className: "flex justify-between items-center py-3 border-b border-white/10 last:border-0", children: [_jsx("span", { className: "text-sm text-white/75", children: s.l }), _jsx("span", { className: "text-lg font-extrabold", children: s.v })] }, s.l)))] })] }) }), _jsx("div", { className: "px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-5xl mx-auto", children: [_jsx("h2", { className: "font-display font-black text-3xl tracking-tight text-center mb-10", children: "Why African institutions choose R-Pro Apply" }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-3 gap-4", children: BENEFITS.map((b) => (_jsxs("div", { className: "card", children: [_jsx("div", { className: "w-11 h-11 bg-brand/10 rounded-xl flex items-center justify-center text-xl mb-3", children: b.icon }), _jsx("p", { className: "font-bold mb-1.5", children: b.title }), _jsx("p", { className: "text-sm text-muted leading-relaxed", children: b.desc })] }, b.title))) })] }) }), _jsx("div", { className: "bg-soft px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-5xl mx-auto", children: [_jsx("h2", { className: "font-display font-black text-2xl tracking-tight text-center mb-10", children: "Onboard in 4 simple steps" }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-4 gap-6", children: STEPS.map((s) => (_jsxs("div", { children: [_jsx("div", { className: "w-10 h-10 bg-brand text-white rounded-full flex items-center justify-center font-bold mb-3", children: s.n }), _jsx("p", { className: "font-bold mb-1.5", children: s.title }), _jsx("p", { className: "text-sm text-muted leading-relaxed", children: s.desc })] }, s.n))) })] }) }), _jsx("div", { className: "px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-2xl mx-auto bg-ink text-white rounded-2xl p-12 text-center", children: [_jsx("h2", { className: "font-display font-black text-3xl tracking-tight mb-3", children: "Ready to grow your enrolment?" }), _jsx("p", { className: "text-white/70 mb-7", children: "Register your institution and our Partner Relations team will reach out within 48 hours." }), _jsx(Link, { to: "/register", className: "btn-primary inline-block", children: "Request Partnership \u2192" })] }) }), _jsx(Footer, {})] }));
}
