import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import TopNav from "../../components/TopNav";
import Footer from "../../components/Footer";
const CATEGORIES = [
    { icon: "📚", title: "Test Prep & Tutoring", desc: "JAMB, WAEC, NECO, UTME, IELTS, TOEFL, SAT" },
    { icon: "🎯", title: "Admissions Consulting", desc: "Application coaching, essay review, interviews" },
    { icon: "📄", title: "Document Services", desc: "WAEC verification, transcripts, notarization" },
    { icon: "🏠", title: "Student Accommodation", desc: "Hostels, off-campus housing, short-lets" },
    { icon: "✈️", title: "Regional Travel & Visa", desc: "Student visa processing for cross-border study" },
    { icon: "🩺", title: "Student Health Services", desc: "Health checks, vaccinations, insurance" },
];
const BENEFITS = [
    { icon: "🎯", title: "Pre-qualified student leads", desc: "Reach only students actively planning their applications — higher intent, higher conversion." },
    { icon: "🔗", title: "Pre-integrated with applications", desc: "Students attach your service directly to their application. No re-registration." },
    { icon: "💰", title: "Commission-only pricing", desc: "No monthly fees — you only pay when we deliver a paying customer." },
];
export default function VendorsPage() {
    return (_jsxs("div", { className: "font-sans bg-white text-ink", children: [_jsx(TopNav, {}), _jsx("div", { className: "bg-gradient-to-br from-info to-[#0C647F] text-white px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-5xl mx-auto grid md:grid-cols-[1.2fr_1fr] gap-12 items-center", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-widest text-white/60 font-bold mb-3", children: "Service Vendors" }), _jsxs("h1", { className: "font-display font-black text-5xl tracking-tight leading-tight mb-5", children: ["Reach every African student", _jsx("br", {}), "who needs your service."] }), _jsx("p", { className: "text-white/80 leading-relaxed mb-7", children: "Whether you offer test prep, study loans, visa processing, or accommodation \u2014 R-Pro Apply connects you to verified students actively planning their African higher education journey." }), _jsx(Link, { to: "/register", className: "inline-block bg-white text-info rounded-lg px-5 py-2.5 text-sm font-bold", children: "List Your Service \u2192" })] }), _jsxs("div", { className: "bg-white/10 border border-white/15 rounded-2xl p-7", children: [_jsx("p", { className: "text-xs uppercase tracking-widest text-white/60 font-bold mb-4", children: "Vendor Reach" }), [
                                    { l: "Countries Reached", v: "54" },
                                    { l: "Add-On Services Attached", v: "12K+/mo" },
                                    { l: "Verified Vendor Partners", v: "120+" },
                                ].map((s) => (_jsxs("div", { className: "flex justify-between items-center py-3 border-b border-white/15 last:border-0", children: [_jsx("span", { className: "text-sm text-white/85", children: s.l }), _jsx("span", { className: "text-lg font-extrabold", children: s.v })] }, s.l)))] })] }) }), _jsx("div", { className: "px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-5xl mx-auto", children: [_jsx("h2", { className: "font-display font-black text-3xl tracking-tight text-center mb-10", children: "What services do students need?" }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-3 gap-4", children: CATEGORIES.map((c) => (_jsxs("div", { className: "card", children: [_jsx("p", { className: "text-2xl mb-2", children: c.icon }), _jsx("p", { className: "font-bold text-sm mb-1", children: c.title }), _jsx("p", { className: "text-xs text-muted leading-relaxed", children: c.desc })] }, c.title))) })] }) }), _jsx("div", { className: "bg-soft px-6 md:px-8 py-16", children: _jsxs("div", { className: "max-w-5xl mx-auto", children: [_jsx("h2", { className: "font-display font-black text-3xl tracking-tight text-center mb-10", children: "Why list your service on R-Pro Apply?" }), _jsx("div", { className: "grid sm:grid-cols-3 gap-4", children: BENEFITS.map((b) => (_jsxs("div", { className: "card", children: [_jsx("div", { className: "w-11 h-11 bg-info/10 rounded-xl flex items-center justify-center text-xl mb-3", children: b.icon }), _jsx("p", { className: "font-bold mb-1.5", children: b.title }), _jsx("p", { className: "text-sm text-muted leading-relaxed", children: b.desc })] }, b.title))) })] }) }), _jsxs("div", { className: "bg-gradient-to-br from-info to-[#0C647F] px-6 md:px-8 py-16 text-center text-white", children: [_jsx("h2", { className: "font-display font-black text-3xl tracking-tight mb-3", children: "Ready to reach African students?" }), _jsx("p", { className: "text-white/85 max-w-xl mx-auto mb-6", children: "Complete vendor onboarding \u2014 our Vendor Success team will reach out within 3 working days." }), _jsx(Link, { to: "/register", className: "inline-block bg-white text-info rounded-lg px-6 py-3 text-sm font-bold", children: "List Your Service \u2192" })] }), _jsx(Footer, {})] }));
}
